Refactor release workflow: add step to identify VSIX file and update asset upload path

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -66,10 +66,17 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 
-      - name: Debug build output
+      - name: Identify VSIX file
+        id: find_vsix
         run: |
-          pwd
-          tree -I node_modules
+          VSIX_FILE=$(ls *.vsix | head -n 1)
+          if [ -z "$VSIX_FILE" ]; then
+            echo "Error: No .vsix file found!" >&2
+            exit 1
+          fi
+          echo "vsix_file=$VSIX_FILE" >> $GITHUB_ENV
+          echo "::set-output name=vsix_file::$VSIX_FILE"
+          echo "Generated VSIX file: ${{ env.vsix_file }}"
 
 
       # Step 9: Upload the VSIX file
@@ -77,6 +84,6 @@ jobs:
         uses: actions/upload-release-asset@v1
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}  # Use the captured URL
-          asset_path: ./*.vsix
+          asset_path: '${{ env.vsix_file }}'
           asset_name: '${{ env.release_tag }}.vsix'
           asset_content_type: application/octet-stream
